### ISSUE TITLE
Embed Peertube videos

### ISSUE THREAD

**Issue by 3615pipou** [splitbrain/dokuwiki-plugin-vshare#90]
Hi,

Could it be possible to embeded PeerTube Video ? [PeerTube](https://joinpeertube.org/en_US/) is a software, the free and decentralized alternative to video platforms developed by [Framasoft](https://framasoft.org/en/) a French association and backed [by Debian](https://bits.debian.org/2020/10/debian-donation-peertube.html). It's base on WebTorrent. You can find some [examples here](https://video.blender.org/search?categoryOneOf=10).

**Comment by nderambure** [comment]
Hello, I've tried to support embed from a Peertube instance (https://tube.futuretic.fr) I managed by adding this lines in this 2 files : 

**sites.conf** : 

`
futuretic       iframe  https://tube.futuretic.fr/videos/embed/@VIDEO@
`

**sites.js** :

`
'futuretic':   'tube\\.futuretic\\.fr\\/videos\\/watch\\/([a-z0-9_\\-]+)'
`

But nothing happen. The JS matched pattern works and create the right wiki syntax, but the iframe is not created...
Since your issue creation is 8 month old and no answer from the developper, I'm not sure there will be any follow...

**Comment by 3615pipou** [comment]
Thanks for your feedback ! Sad to see it doesn't work :disappointed: 
 @splitbrain could you take a look at it ? As already explain PeerTube is a stable, active and promising project :smiley:  (they have just release the 3.4 https://joinpeertube.org/en_US/news#release-3.4 )
Even main bittorrent clients as libtorrent are working to improve it https://feross.org/libtorrent-webtorrent/

**Comment by splitbrain** [comment]
From what I understand, peertube is federated. it makes no sense to support only one instance and it's impossible to support all of them. so I am not sure what I can do here but close the ticket?

**Comment by 3615pipou** [comment]
Well I see the problem. Thank you for answering ! 
After reading your response I've tried again to find a solution and... I found it :smile: 

Peertube is using oEmbed and there is a DokuWiki plugin "to easily embed media from any provider that supports the oEmbed format." and it works ! https://www.dokuwiki.org/plugin:oembed

Maybe you could add this sentence in Video Share Plugin's documentation, since it's way more popular than oEmbed plugin :
"For other video sharing sites not supported by vshare, particularly those using PeerTube, you could use the [oEmbed plugin](https://www.dokuwiki.org/plugin:oembed)"

**Comment by 3615pipou** [comment]
The two plugins should maybe be merged ?
